<?php
	$acf_layout = array (
				'label' => 'Button',
				'name' => 'button',
				'display' => 'row',
				'min' => '',
				'max' => '',
				'sub_fields' => array (
					$acf_background,
					$acf_background_image,
					array (
						'key' => 'field_button_1000000000001',
						'label' => 'Button Type',
						'name' => 'button_type',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'page' => 'Page',
							'link' => 'Link',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_button_1000000000002',
						'label' => 'Button Text',
						'name' => 'button_text',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_button_1000000000003',
						'label' => 'Button Link',
						'name' => 'button_link',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_button_1000000000001',
									'operator' => '==',
									'value' => 'link',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => 'http://',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_button_1000000000004',
						'label' => 'Button Page',
						'name' => 'button_page',
						'type' => 'page_link',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_button_1000000000001',
									'operator' => '==',
									'value' => 'page',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'post_type' => array (
							0 => 'post',
							1 => 'page',
							2 => 'product',
							3 => 'locations',
							4 => 'resources',
						),
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
			);
?>